version: "3.1"
networks:
  shared:
    external: true

services:
  peer_ssh:
    image: opny/peer-ssh-client
    volumes:
      - ./example:/app/example
      - ./src:/app/src
    networks:
      - shared
